name: Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@185.142.99.51
      DEPLOY_DIRECTORY: /root/superserver
      CONFIG_PATH:

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build and deploy using Makefile
        run: |
          make install

      - name: Copy files to the server
        uses: appleboy/scp-action@v0.2.3
        with:
          host: 185.142.99.51
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          source: "$(APP_NAME) $(SERVICE_NAME)"
          target: "$(APP_PATH)"

      - name: SSH into server and stop the service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 185.142.99.51
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo make stop

      - name: Reload systemd and restart the service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 185.142.99.51
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo make reload
            sudo make start
